### ISSUE TITLE
El juego termina antes de que se coloque la cantidad de fichas elegidas

### ISSUE THREAD

**Issue by Grinchuelo** [RomanFama592/tic-tac-toe-world#1]
El bug aparece cuando selecciono la cantidad de piezas conectadas para ganar en: 5 Cuando un jugador coloca sus fichas en este orden de ejemplo: 1;1 , 2;2 , 4;4 , 3;3
automáticamente el juego se termina a pesar de que las fichas colocadas hayan sido solo 4.
El problema aparece tanto en diagonal como en horizontal: Supongamos que elegís la cantidad de piezas conectadas para ganar en: 4. En donde si por ejemplo, un jugador coloca sus fichas en este orden: 1;1 , 1;3 , 1;2 el juego también termina aunque sólo se hayan colocado 3 fichas en lugar de 4.

**Comment by RomanFama592** [comment]
Muchas gracias por comentar este problema ya lo estoy solucionando
